lib/school_house_web/router.ex
defmodule SchoolHouseWeb.Router do
  use SchoolHouseWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, html: {SchoolHouseWeb.Layouts, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug SchoolHouseWeb.RedirectPlug
    plug SchoolHouseWeb.SetLocalePlug
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", SchoolHouseWeb do
    pipe_through :browser

    get "/", PageController, :index

    get "/blog", PostController, :index
    get "/blog/:slug", PostController, :show
    get "/blog/tag/:tag", PostController, :filter_by_tag

    get "/privacy", PageController, :privacy

    scope "/:locale" do
      get "/", PageController, :index
      get "/why", PageController, :why
      get "/get_involved", PageController, :get_involved
      get "/podcasts", PageController, :podcasts
      live "/conferences", ConferencesLive

      get "/report", ReportController, :index

      get "/lessons/:section", LessonController, :index
      get "/lessons/:section/:name", LessonController, :lesson
    end
  end
end

lib/school_house_web/views/layout_view.ex
defmodule SchoolHouseWeb.LayoutView do
  use SchoolHouseWeb, :view

  use PhoenixHTMLHelpers

  def render_dark_mode?(conn) do
    case conn.query_params do
      %{"ui" => "dark"} -> "dark"
      _ -> ""
    end
  end
end

lib/school_house_web/templates/layout/_dark_mode_toggle.html.heex
<div id="dark-mode-toggle-container" class="flex items-center cursor-pointer">
  <div class="relative">
    <input type="checkbox" id="dark-mode-toggle" class="sr-only" aria-label="Dark Mode Toggle">
    <div class="block bg-gray-600 w-14 h-8 rounded-full">
    </div>
    <div class="dot absolute left-1 top-1 bg-body dark:bg-purple-dark w-6 h-6 rounded-full flex items-center justify-center transition-all">
      <svg id="moon-icon" viewBox="0 0 97 158" version="1.1" xmlns="http://www.w3.org/2000/svg" fill="currentColor" stroke="currentColor" stroke-width="2" class="h-4 ml-1 text-white">
        <path d="M18,0.5 C39.6771764,0.5 59.3021764,9.28641179 73.5078823,23.4921177 C87.7135882,37.6978236 96.5,57.3228236 96.5,79 C96.5,100.677176 87.7135882,120.302176 73.5078823,134.507882 C59.3021764,148.713588 39.6771764,157.5 18,157.5 C12.5891637,157.5 7.30617797,156.952622 2.20396947,155.909667 C19.0949556,151.484612 33.7935641,141.64268 44.331072,128.351675 C55.0804392,114.793451 61.5,97.6464258 61.5,79 C61.5,60.3535766 55.0804409,43.2065533 44.3310574,29.6483015 C33.7928623,16.3564226 19.093019,6.51402742 2.20435475,2.0894815 C7.30689791,1.047303 12.5895324,0.5 18,0.5 Z"></path>
      </svg>
      <svg id="sun-icon" viewBox="0 0 170 170" version="1.1" xmlns="http://www.w3.org/2000/svg" stroke="currentColor" fill="currentColor" class="h-4 text-black">
        <g id="Group-2" transform="translate(80.000000, 79.000000) rotate(-4.000000) translate(-80.000000, -79.000000) translate(1.000000, -0.000000)">
          <circle id="Oval" cx="79" cy="79" r="22.5"></circle>
          <g id="Group" stroke-linecap="square" stroke-width="5" stroke="currentColor">
            <line x1="111.085701" y1="51.5309469" x2="139.247251" y2="27.5243795"></line>
            <line x1="121.11157" y1="82.2644628" x2="158" y2="85.2024793"></line>
            <line x1="104.160729" y1="137.400592" x2="132.783944" y2="112.93236" transform="translate(118.472337, 125.166476) rotate(90.000000) translate(-118.472337, -125.166476) "></line>
            <line x1="75.7355372" y1="121.11157" x2="72.7975207" y2="158"></line>
            <line x1="18.7527491" y1="130.475621" x2="46.9142993" y2="106.469053" transform="translate(32.833524, 118.472337) rotate(180.000000) translate(-32.833524, -118.472337) "></line>
            <line x1="36.8884298" y1="75.7355372" x2="0" y2="72.7975207"></line>
            <line x1="25.2160557" y1="45.0676403" x2="53.8392707" y2="20.5994081" transform="translate(39.527663, 32.833524) rotate(270.000000) translate(-39.527663, -32.833524) "></line>
            <line x1="82.2644628" y1="36.8884298" x2="85.2024793" y2="0"></line>
          </g>
        </g>
      </svg>
    </div>
  </div>
</div>

lib/school_house_web/templates/layout/_footer.html.heex
<footer class="mt-16 bg-footer dark:bg-footer-dark" aria-labelledby="footerHeading">
  <p id="footerHeading" class="sr-only">Footer</p>
  <div class="px-4 py-12 mx-auto max-w-7xl sm:px-6 lg:py-16 lg:px-8">
    <div class="xl:grid xl:grid-cols-3 xl:gap-8">
      <div class="space-y-8 xl:col-span-1">
        <div class="flex items-center">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 p-2 text-white rounded-full bg-purple dark:bg-purple-dark" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19.428 15.428a2 2 0 00-1.022-.547l-2.387-.477a6 6 0 00-3.86.517l-.318.158a6 6 0 01-3.86.517L6.05 15.21a2 2 0 00-1.806.547M8 4h8l-1 1v5.172a2 2 0 00.586 1.414l5 5c1.26 1.26.367 3.414-1.415 3.414H4.828c-1.782 0-2.674-2.154-1.414-3.414l5-5A2 2 0 009 10.172V5L8 4z" />
          </svg>
          <span class="ml-3 text-xl text-heavy dark:text-heavy-dark"><%= gettext("Elixir School")%></span>
        </div>
        <p class="text-base italic text-lighter dark:text-lighter-dark">
          <%= gettext("The premier destination for learning and mastering Elixir")%>
        </p>
        <div class="flex space-x-6">

          <a href="https://twitter.com/elixirschool" class="text-light dark:text-light-dark hover:text-gray-500">
            <span class="sr-only">Twitter</span>
            <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
              <path d="M8.29 20.251c7.547 0 11.675-6.253 11.675-11.675 0-.178 0-.355-.012-.53A8.348 8.348 0 0022 5.92a8.19 8.19 0 01-2.357.646 4.118 4.118 0 001.804-2.27 8.224 8.224 0 01-2.605.996 4.107 4.107 0 00-6.993 3.743 11.65 11.65 0 01-8.457-4.287 4.106 4.106 0 001.27 5.477A4.072 4.072 0 012.8 9.713v.052a4.105 4.105 0 003.292 4.022 4.095 4.095 0 01-1.853.07 4.108 4.108 0 003.834 2.85A8.233 8.233 0 012 18.407a11.616 11.616 0 006.29 1.84" />
            </svg>
          </a>

          <a href="https://github.com/elixirschool" class="text-light dark:text-light-dark hover:text-gray-500">
            <span class="sr-only">GitHub</span>
            <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
              <path fill-rule="evenodd" d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z" clip-rule="evenodd" />
            </svg>
          </a>

        </div>
      </div>
      <div class="mt-12 grid grid-cols-2 gap-8 xl:mt-2 xl:col-span-2">
        <div class="md:grid md:grid-cols-2 md:gap-8">
          <div>
            <p class="text-sm font-semibold tracking-wider text-lighter dark:text-lighter-dark uppercase">
              <%= gettext("Getting Started")%>
            </p>
            <ul class="mt-4 space-y-4">
              <li>
                <%= link(gettext("Why Elixir?"), to: Routes.page_path(@conn, :why, current_locale()), class: "text-base text-light dark:text-light-dark hover:text-gray-900") %>
              </li>
              <li>
                <%= link(gettext("Podcasts"), to: Routes.page_path(@conn, :podcasts, current_locale()), class: "text-base text-light dark:text-light-dark hover:text-gray-900") %>
              </li>
              <li>
                <%= link(gettext("Conferences"), to: Routes.live_path(@conn, SchoolHouseWeb.ConferencesLive, current_locale()), class: "text-base text-light dark:text-light-dark hover:text-gray-900") %>
              </li>
            </ul>
          </div>
          <div class="mt-12 md:mt-0">
            <p class="text-sm font-semibold tracking-wider text-lighter dark:text-lighter-dark uppercase">
              <%= gettext("Lessons") %>
            </p>
            <ul class="mt-4 space-y-4">
              <li>
                <%= link(gettext("Basics"), to: Routes.lesson_path(@conn, :index, current_locale(), :basics), class: "text-base text-light dark:text-light-dark hover:text-gray-900") %>
              </li>

              <li>
                <%= link(gettext("Intermediate"), to: Routes.lesson_path(@conn, :index, current_locale(), :intermediate), class: "text-base text-light dark:text-light-dark hover:text-gray-900") %>
              </li>

              <li>
                <%= link(gettext("Advanced"), to: Routes.lesson_path(@conn, :index, current_locale(), :advanced), class: "text-base text-light dark:text-light-dark hover:text-gray-900") %>
              </li>

              <li>
                <%= link(gettext("Testing"), to: Routes.lesson_path(@conn, :index, current_locale(), :testing), class: "text-base text-light dark:text-light-dark hover:text-gray-900") %>
              </li>

              <li>
                <%= link(gettext("Data Processing"), to: Routes.lesson_path(@conn, :index, current_locale(), :data_processing), class: "text-base text-light dark:text-light-dark hover:text-gray-900") %>
              </li>

              <li>
                <%= link(gettext("Ecto"), to: Routes.lesson_path(@conn, :index, current_locale(), :ecto), class: "text-base text-light dark:text-light-dark hover:text-gray-900") %>
              </li>

              <li>
                <%= link(gettext("Storage"), to: Routes.lesson_path(@conn, :index, current_locale(), :storage), class: "text-base text-light dark:text-light-dark hover:text-gray-900") %>
              </li>

              <li>
                <%= link(gettext("Miscellaneous"), to: Routes.lesson_path(@conn, :index, current_locale(), :misc), class: "text-base text-light dark:text-light-dark hover:text-gray-900") %>
              </li>
            </ul>
          </div>
        </div>
        <div class="md:grid md:grid-cols-2 md:gap-8">
          <div>
            <p class="text-sm font-semibold tracking-wider text-lighter dark:text-lighter-dark uppercase">
              <%= link(gettext("Blog"), to: Routes.post_path(@conn, :index), class: "hover:text-gray-600") %>
            </p>
            <ul class="mt-4 space-y-4">
              <li>
                <%= link(gettext("Announcements"), to: Routes.post_path(@conn, :filter_by_tag, "announcement"), class: "text-base text-light dark:text-light-dark hover:text-gray-900") %>
              </li>

              <li>
                <%= link(gettext("Today I Learned (TIL)"), to: Routes.post_path(@conn, :filter_by_tag, "til"), class: "text-base text-light dark:text-light-dark hover:text-gray-900") %>
              </li>

              <li>
                <%= link(gettext("Reviews"), to: Routes.post_path(@conn, :filter_by_tag, "review"), class: "text-base text-light dark:text-light-dark hover:text-gray-900") %>
              </li>

            </ul>
          </div>
          <div class="mt-12 md:mt-0">
            <p class="text-sm font-semibold tracking-wider text-lighter dark:text-lighter-dark uppercase">
              <%= gettext("Project")%>
            </p>
            <ul class="mt-4 space-y-4">
              <li>
                <%= link(gettext("Get Involved"), to: Routes.page_path(@conn, :get_involved, current_locale()), class: "text-base text-light dark:text-light-dark hover:text-gray-900") %>
              </li>
              <%= if current_locale() != "en" do %>
                <li>
                  <%= link gettext("Translation Report"), to: Routes.report_path(@conn, :index, current_locale()), class: "text-base text-light dark:text-light-dark hover:text-gray-900" %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="pt-8 mt-12 border-t border-gray-200">
      <p class="text-base text-lighter dark:text-lighter-dark xl:text-center">
        &copy; 2021 Sean Callan —
        <a href="https://twitter.com/doomspork" rel="noopener noreferrer"  class="text-base text-light dark:text-light-dark hover:text-gray-900" target="_blank">@doomspork</a>
      </p>
    </div>
  </div>
</footer>

lib/school_house_web/templates/layout/_footer.html.leex
<footer class="mt-16 bg-footer dark:bg-footer-dark" aria-labelledby="footerHeading">
  <h2 id="footerHeading" class="sr-only">Footer</h2>
  <div class="px-4 py-12 mx-auto max-w-7xl sm:px-6 lg:py-16 lg:px-8">
    <div class="xl:grid xl:grid-cols-3 xl:gap-8">
      <div class="space-y-8 xl:col-span-1">
        <div class="flex items-center">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 p-2 text-white rounded-full bg-purple dark:bg-purple-dark" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19.428 15.428a2 2 0 00-1.022-.547l-2.387-.477a6 6 0 00-3.86.517l-.318.158a6 6 0 01-3.86.517L6.05 15.21a2 2 0 00-1.806.547M8 4h8l-1 1v5.172a2 2 0 00.586 1.414l5 5c1.26 1.26.367 3.414-1.415 3.414H4.828c-1.782 0-2.674-2.154-1.414-3.414l5-5A2 2 0 009 10.172V5L8 4z" />
          </svg>
          <span class="ml-3 text-xl text-heavy dark:text-heavy-dark">Elixir School</span>
        </div>
        <p class="text-base italic text-lighter dark:text-lighter-dark">
          The premier destination for learning and mastering Elixir
        </p>
        <div class="flex space-x-6">

          <a href="https://twitter.com/elixirschool" class="text-light dark:text-light-dark hover:text-gray-500">
            <span class="sr-only">Twitter</span>
            <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
              <path d="M8.29 20.251c7.547 0 11.675-6.253 11.675-11.675 0-.178 0-.355-.012-.53A8.348 8.348 0 0022 5.92a8.19 8.19 0 01-2.357.646 4.118 4.118 0 001.804-2.27 8.224 8.224 0 01-2.605.996 4.107 4.107 0 00-6.993 3.743 11.65 11.65 0 01-8.457-4.287 4.106 4.106 0 001.27 5.477A4.072 4.072 0 012.8 9.713v.052a4.105 4.105 0 003.292 4.022 4.095 4.095 0 01-1.853.07 4.108 4.108 0 003.834 2.85A8.233 8.233 0 012 18.407a11.616 11.616 0 006.29 1.84" />
            </svg>
          </a>

          <a href="https://github.com/elixirschool" class="text-light dark:text-light-dark hover:text-gray-500">
            <span class="sr-only">GitHub</span>
            <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
              <path fill-rule="evenodd" d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z" clip-rule="evenodd" />
            </svg>
          </a>

        </div>
      </div>
      <div class="mt-12 grid grid-cols-2 gap-8 xl:mt-2 xl:col-span-2">
        <div class="md:grid md:grid-cols-2 md:gap-8">
          <div>
            <h3 class="text-sm font-semibold tracking-wider text-lighter dark:text-lighter-dark uppercase">
              Getting Started
            </h3>
            <ul class="mt-4 space-y-4">
              <li>
                <%= link(gettext("Why Elixir?"), to: Routes.page_path(@conn, :why, current_locale()), class: "text-base text-light dark:text-light-dark hover:text-gray-900") %>
              </li>
              <li>
                <%= link(gettext("Podcasts"), to: Routes.page_path(@conn, :podcasts, current_locale()), class: "text-base text-light dark:text-light-dark hover:text-gray-900") %>
              </li>
              <li>
                <%= link(gettext("Conferences"), to: Routes.live_path(@conn, SchoolHouseWeb.ConferencesLive, current_locale()), class: "text-base text-light dark:text-light-dark hover:text-gray-900") %>
              </li>
            </ul>
          </div>
          <div class="mt-12 md:mt-0">
            <h3 class="text-sm font-semibold tracking-wider text-lighter dark:text-lighter-dark uppercase">
              <%= gettext("Lessons") %>
            </h3>
            <ul class="mt-4 space-y-4">
              <li>
                <%= link(gettext("Basics"), to: Routes.lesson_path(@conn, :index, current_locale(), :basics), class: "text-base text-light dark:text-light-dark hover:text-gray-900") %>
              </li>

              <li>
                <%= link(gettext("Intermediate"), to: Routes.lesson_path(@conn, :index, current_locale(), :intermediate), class: "text-base text-light dark:text-light-dark hover:text-gray-900") %>
              </li>

              <li>
                <%= link(gettext("Advanced"), to: Routes.lesson_path(@conn, :index, current_locale(), :advanced), class: "text-base text-light dark:text-light-dark hover:text-gray-900") %>
              </li>

              <li>
                <%= link(gettext("Testing"), to: Routes.lesson_path(@conn, :index, current_locale(), :testing), class: "text-base text-light dark:text-light-dark hover:text-gray-900") %>
              </li>

              <li>
                <%= link(gettext("Data Processing"), to: Routes.lesson_path(@conn, :index, current_locale(), :data_processing), class: "text-base text-light dark:text-light-dark hover:text-gray-900") %>
              </li>

              <li>
                <%= link(gettext("Ecto"), to: Routes.lesson_path(@conn, :index, current_locale(), :ecto), class: "text-base text-light dark:text-light-dark hover:text-gray-900") %>
              </li>

              <li>
                <%= link(gettext("Storage"), to: Routes.lesson_path(@conn, :index, current_locale(), :storage), class: "text-base text-light dark:text-light-dark hover:text-gray-900") %>
              </li>

              <li>
                <%= link(gettext("Miscellaneous"), to: Routes.lesson_path(@conn, :index, current_locale(), :misc), class: "text-base text-light dark:text-light-dark hover:text-gray-900") %>
              </li>
            </ul>
          </div>
        </div>
        <div class="md:grid md:grid-cols-2 md:gap-8">
          <div>
            <h3 class="text-sm font-semibold tracking-wider text-lighter dark:text-lighter-dark uppercase">
              <%= link("Blog", to: Routes.post_path(@conn, :index), class: "hover:text-gray-600") %>
            </h3>
            <ul class="mt-4 space-y-4">
              <li>
                <%= link("Announcements", to: Routes.post_path(@conn, :filter_by_tag, "announcement"), class: "text-base text-light dark:text-light-dark hover:text-gray-900") %>
              </li>

              <li>
                <%= link("Today I Learned (TIL)", to: Routes.post_path(@conn, :filter_by_tag, "til"), class: "text-base text-light dark:text-light-dark hover:text-gray-900") %>
              </li>

              <li>
                <%= link("Reviews", to: Routes.post_path(@conn, :filter_by_tag, "review"), class: "text-base text-light dark:text-light-dark hover:text-gray-900") %>
              </li>

            </ul>
          </div>
          <div class="mt-12 md:mt-0">
            <h3 class="text-sm font-semibold tracking-wider text-lighter dark:text-lighter-dark uppercase">
              Project
            </h3>
            <ul class="mt-4 space-y-4">
              <li>
                <%= link("Get Involved", to: Routes.page_path(@conn, :get_involved, current_locale()), class: "text-base text-light dark:text-light-dark hover:text-gray-900") %>
              </li>
              <%= if current_locale() != "en" do %>
                <li>
                  <%= link gettext("Translation Report"), to: Routes.report_path(@conn, :index, current_locale()), class: "text-base text-light dark:text-light-dark hover:text-gray-900" %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="pt-8 mt-12 border-t border-gray-200">
      <p class="text-base text-lighter dark:text-lighter-dark xl:text-center">
        &copy; 2021 Sean Callan —
        <a href="https://twitter.com/doomspork" rel="noopener noreferrer"  class="text-base text-light dark:text-light-dark hover:text-gray-900" target="_blank">@doomspork</a>
      </p>
    </div>
  </div>
</footer>

lib/school_house_web/templates/layout/_header.html.heex
<div class="flex flex-row fixed md:relative h-full md:h-auto z-10 md:w-full">
  <nav id="nav" class="w-64 md:w-full relative bg-nav dark:bg-nav-dark md:border-b-4 border-brand-purple-800 text-primary dark:text-primary-dark shadow-md transition-margin duration-300 overflow-y-scroll md:overflow-y-visible -ml-64 md:ml-0">
    <div class="container mx-auto flex flex-col md:flex-row justify-between">
      <%= link(to: Routes.page_path(@conn, :index, current_locale()), class: "flex title-font font-medium items-center text-heavy dark:text-heavy-dark mb-4 md:mb-0 mx-auto md:mx-2 mt-6 md:mt-0") do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 md:w-7 md:h-7 lg:h-10 lg:w-10 p-2 text-white rounded-full bg-purple" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19.428 15.428a2 2 0 00-1.022-.547l-2.387-.477a6 6 0 00-3.86.517l-.318.158a6 6 0 01-3.86.517L6.05 15.21a2 2 0 00-1.806.547M8 4h8l-1 1v5.172a2 2 0 00.586 1.414l5 5c1.26 1.26.367 3.414-1.415 3.414H4.828c-1.782 0-2.674-2.154-1.414-3.414l5-5A2 2 0 009 10.172V5L8 4z" />
        </svg>
        <span class="ml-3 text-2xl font-extrabold text-primary dark:text-primary-dark tracking-tight"><%= gettext("Elixir School")%></span>
      <% end %>
      <div class="w-full md:w-auto mx-auto md:ml-auto md:mr-0 flex flex-col-reverse md:flex-row">
        <ul class="flex flex-col md:flex-row md:items-center">
          <li class="hover:bg-purple hover:text-white px-4 md:px-0">
            <%= link(gettext("Why Elixir?"), to: Routes.page_path(@conn, :why, current_locale()), class: "relative block py-6 px-4 lg:p-6 text-sm md:text-center lg:text-base font-bold") %>
          </li>
          <li class="toggleable hover:bg-purple hover:text-white px-4 md:px-0">
            <%= render("_lesson_menu.html", conn: @conn) %>
          </li>
          <li class="hover:bg-purple hover:text-white px-4 md:px-0">
            <%= link(gettext("Blog"), to: Routes.post_path(@conn, :index), class: "relative block py-6 px-4 lg:p-6 text-sm md:text-center lg:text-base font-bold") %>
          </li>
          <li class="hover:bg-purple hover:text-white px-4 md:px-0">
            <%= link(gettext("Get Involved"), to: Routes.page_path(@conn, :get_involved, current_locale()), class: "relative block py-6 px-4 lg:p-6 text-sm md:text-center lg:text-base font-bold") %>
          </li>
        </ul>
        <ul class="flex flex-row items-center justify-center py-4 md:py-0">
          <li class="inline-flex items-center md:justify-center px-4 md:px-2">
            <%= render("_dark_mode_toggle.html", conn: @conn) %>
          </li>
          <li class="inline-flex items-center md:justify-center px-4 md:ml-2">
            <%= render("_locale_menu.html", conn: @conn) %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div id="menu-toggle-button" class="md:hidden w-8 h-8 mt-4 ml-4 text-primary dark:text-primary-dark cursor-pointer">
    <svg fill="currentColor" class="px-2 py-1 bg-nav dark:bg-nav-dark shadow-md rounded-md" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
  </div>
</div>